### ISSUE TITLE
OpenGL stereo greyed out

### ISSUE THREAD

**Issue by ThreeDeeJay** [marlam/bino#46]
I'm trying to get bino to output 3D on my NVIDIA 3D Vision setup, but the option is greyed out:
<img width="159" height="195" alt="Image" src="https://github.com/user-attachments/assets/c5ed8a45-ba29-4aa1-abe2-a2e11a36e753" />

I know almost everywhere it's claimed that OpenGL quad-buffer stereo 3D only works on the Quadro/professional cards, but I've been able to use it in several apps/games like sView, SpaceEngine, DarkPlaces engine, etc. with an RTX 2080 Ti and GeForce driver 425.31 (last official 3D Vision driver).

Even PyMol explicitly detects it
<img width="526" height="156" alt="Image" src="https://github.com/user-attachments/assets/bb6b2f4a-5d1c-44e8-acaf-2564f5272f75" />

And I've noticed that OGL 3D often requires fullscreen, specifically exclusive, and some apps like ATOMS require going into fullscreen with D3D once before switching to OGL, though the [sView dev managed to force exclusive fullscreen in OpenGL](https://github.com/gkv311/sview/issues/156#issuecomment-3023287342), which fixed quad-buffer 3D on my setup without having to switch from D3D.

**Comment by marlam** [comment]
The OpenGL quad-buffered stereo mode must currently be explicitly requested at startup time using the `--stereo` option:
```
$ bino --stereo
```

Can you please try this?


More details: This restriction is because autodetection is (or at least was) broken by the Qt abstractions. The comment in the source code about this issue reads as follows:
```
        // The user has to explicitly request stereo mode, we cannot simply
        // try it and fall back to normal mode if it is not available:
        // Somehow Qt messes up something in the OpenGL context or widget setup
        // when stereo was requested but is not available. This was a problem at
        // least from Qt 5.7-5.9 (see comments in Bino 1.x src/video_output_qt.cpp),
        // and now again with Qt 6.3.
        // So now we only try to use it when explicitly requested, and we immediately
        // quit when we don't get it (see Bino::initializeGL).
```

This may not be a problem with the latest Qt versions anymore, but I cannot test it since I don't have access to a system that supports quad-buffered stereo.

**Comment by ThreeDeeJay** [comment]
I see. That option indeed runs bino with OpenGL Stereo, and going fullscreen activates 3D mode, but the right eye isn't rendered (black frame). If I try swapping eyes with F7, then my left eye sees the right view, but the right eye is still getting a black frame. 🤔

**Comment by marlam** [comment]
Apparently there were changes in Qt 6.5 in how quad-buffered OpenGL works with QOpenGLWidget.

I added a patch that should fix the issue in theory, but I cannot test it -- would you be so kind to test this latest version?

If it works, we could also check if autodetection of quad-buffered stereo works again with current Qt, so that the need for the `--stereo` option could be removed.

**Comment by ThreeDeeJay** [comment]
> would you be so kind to test this latest version?

H*ck yeah I can. 

> I added a patch that should fix the issue in theory

That fixed it! Thanks! 👌 

> If it works, we could also check if autodetection of quad-buffered stereo works again with current Qt, so that the need for the `--stereo` option could be removed.

I still need to launch with `--stereo` if that's what you're asking. But if you're referring to a future update, just let me know and I'll give it a go.

On a side note, F11 to toggle fullscreen (which I need for OGL QB 3D) doesn't seem to work. I used 2 keyboards (real and virtual) with the same result. So I just clicked View > Fullscreen and then I have to exit with Esc which quits the whole app.

And by the way, if you or anyone else ever get an OGL QB 3D-capable hardware and need a reference app to test , you can use this: https://www.more3d.com/wp-content/uploads/more3D_Projector_QuadBuffer_Test.exe

**Comment by ThreeDeeJay** [comment]
I just happened to noticed you pushed the update so I compiled it and indeed now it works without `--stereo`. 👀👌 
By the way, is there any reason why _all_ 3D modes are greyed out before loading a file?

**Comment by marlam** [comment]
Oh thanks, I was just about to ask you to test again :)

The reason that all 3D modes are greyed out is that Bino basically falls back to "assume the input is 2D" if no input is open. That may not be a wise choice. I have to think about how the menu system works, it seems I forgot some details...

The fullscreen shortcut problem is also not entirely clear to me. It works on my Linux system. On Windows the following shortcuts should all work: F11, F, Alt+Enter. Does F or Alt+Enter work for you?

**Comment by marlam** [comment]
Ok, the first problem is solved now - you can choose a 3D output mode before loading a file.

**Comment by ThreeDeeJay** [comment]
Neat, can confirm it works on my end. Though shouldn't it save the preference?
After a restart, it reverts back to anaglyph.

As for the hotkeys:
- F works
- Alt + Enter doesn't work but Alt + *Numpad* Enter works. And both left and right Alts work btw.
- Going in and out of fullscreen sometimes ends up with a black frame on the right eye. This only seems to affect OpenGL quad buffer.
- If I spam the toggle quickly, the app crashes.

**Comment by marlam** [comment]
OK, the GUI now remembers the output mode and the last directory.

I added a few safeguards to fullscreen toggling, could you test again?

I cannot see any reason why it would make problems (and it doesn't on my system) so this is again hard to debug...

**Comment by ThreeDeeJay** [comment]
The mode persistence works, but I still get the occasional black right eye and crash when spamming fullscreen toggle.
It might just be some Windows (exclusive?) fullscreen shenanigans so perhaps borderless window might help, but I think exclusive is still needed for OpenGL stereo, at least when using NVIDIA 3D Vision 🤔

**Comment by marlam** [comment]
I'm afraid there's nothing more I can do right now about the fullscreen problems; I cannot reproduce them.

I just released version 2.6 so that at least the GUI and quad-buffer improvements get out there.
